spring.application.name=JPAHibernate
spring.datasource.url=jdbc:postgresql://${ALURA_DB_HOST}/jpahibernate
spring.datasource.username=${ALURA_DB_USER}
spring.datasource.password=${ALURA_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
